name: automount-actions
base: core22
version: '1.0'
summary: Automatically mount USB and take actions
description: |
  This snap waits for USB plug events of block devices and automatically mounts
  such devices under the snap's tmpdir when inserted and then acknowledges the
  assertions and their corresponding snaps on the partitions of that block device.

grade: stable
confinement: strict

# The daemons are installed as disabled because the snapd-control and
# mount-control interfaces are not auto-connecting. They can be installed as
# enabled if interface auto-connection is enabled either in the Store UI or in
# the gadget snap.
apps:
  auto-mount:
    command: usr/bin/auto-mount.sh
    daemon: simple
    install-mode: disable
    plugs: [mntctl]
    # Some environment variables can be modified
    #environment:
    #  FSTYPE: vfat
    #  MOUNT_DIR: /tmp/tmp.XXXXXXXXXX
    #  OPTIONS: rw,sync
    #  WATCH_FILE: /tmp/mounts.fifo

  auto-install:
    command: usr/bin/auto-install.sh
    daemon: simple
    install-mode: disable
    plugs: [mntctl,snapd-control]
    # Some environment variables can be modified
    #environment:
    #  LOG_DIR: /tmp/tmp.XXXXXXXXXX
    #  SNAPD_SOCKET: /run/snapd.socket
    #  WATCH_FILE: /tmp/mounts.fifo

# Add extra mount rules for different devices e.g. SD cards
# Filesystem types and options can be restricted as needed.
# For a full list of accepted filesystem types and mount options, see:
# https://snapcraft.io/docs/mount-control-interface
plugs:
  mntctl:
    interface: mount-control
    mount:
    - what: /dev/sd*
      where: /tmp/**
      type: [ext2, ext3, ext4, vfat]
      options: [rw, sync]

parts:
  actions:
    source: scripts/
    plugin: dump
    stage-packages:
      - curl
      - eject
      - inotify-tools
      - mount
    organize:
      bin:  usr/bin
      sbin: usr/bin
